    drop table if exists authors;

    drop table if exists books;

    drop table if exists genr;

    drop table if exists link_book_genre;

    create table authors (
       id bigint generated by default as identity,
        name varchar(512) not null,
        primary key (id)
    );

    create table books (
       id bigint generated by default as identity,
        name varchar(512) not null,
        author_id integer not null,
        primary key (id)
    );

    create table genr (
       id bigint generated by default as identity,
       name varchar(512) not null,
       primary key (id)
    );

    create table book_genr (
       book_id bigint not null,
       genre_id bigint not null
    );

    alter table books
       add constraint FKfjixh2vym2cvfj3ufxj91jem7
       foreign key (author_id)
       references authors;

    alter table book_genr
       add constraint FKqfbsbxk6s0qvt80prcvf9qo1l
       foreign key (book_id)
       references books;

    alter table book_genr
       add constraint FKmj5kgxs18xfygs0q9wk319xk6
       foreign key (genre_id)
       references genr;
